version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:admin@db:5432/user_auth_fastapi
    depends_on:
      - db
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:13-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=fastapi-auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
